# Generated by Django 4.0.2 on 2022-02-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('balance_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('balance_currency', models.CharField(max_length=10)),
                ('native_amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('native_currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('send', 'Send')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Cancelled')], max_length=50)),
                ('created_at', models.DateTimeField()),
                ('amount_value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('amount_currency', models.CharField(max_length=10)),
                ('native_amount_value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('native_amount_currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('canceled', 'Cancelled'), ('created', 'Created'), ('completed', 'Completed')], max_length=10)),
                ('created_at', models.DateTimeField(null=True)),
                ('fees', models.JSONField(default=dict)),
                ('amount', models.JSONField(default=dict)),
                ('subtotal', models.JSONField(default=dict)),
                ('total', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.account')),
            ],
        ),
    ]
