# Generated by Django 4.0.2 on 2022-02-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('canceled', 'Cancelled'), ('created', 'Created'), ('completed', 'Completed')], max_length=10)),
                ('created_at', models.DateTimeField(null=True)),
                ('fees', models.DecimalField(decimal_places=8, max_digits=30)),
                ('fee_currency', models.CharField(max_length=10)),
                ('price_paid', models.DecimalField(decimal_places=8, max_digits=30)),
                ('price_currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=30)),
                ('amount_currency', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.account')),
            ],
        ),
    ]
