# Generated by Django 4.0.2 on 2022-02-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='fees',
            field=models.JSONField(default=list),
        ),
    ]
